# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "rubocop-github", "~> 0.17.0"
gem "rubocop", "~> 1.48.0"
gem "rubocop-performance", "~>1.19.0"
gem "rubocop-rails", "~> 2.5"
gem "rubocop-rspec", "~> 1.41.0"