---
########
########
## CI ##
########
########
name: Continuous Integration

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
# Don't need to run on push to master/main
on:
  push:
    branches-ignore:
      - 'master'
      - 'main'

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: CI
    # Set the agent to run on
    runs-on: ubuntu-latest
    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2

      ########################
      # Setup Docker build X #
      ########################
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1

      ##############################
      # Build the docker container #
      ##############################
      - name: Build Docker container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_REVISION=${{ github.sha }}
            BUILD_VERSION=${{ github.sha }}
          push: false
          tags: super-cool-image:latest
          outputs: type=docker,dest=/tmp/myimage.tar
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: myimage
          path: /tmp/myimage.tar

  #############################################
  # Second build job to ingest built artifact #
  #############################################
  use:
    runs-on: ubuntu-latest
    needs: build
    steps:
      #######################
      # Setup docker buildx #
      #######################
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      ###############################################
      # Download the artifact from GitHub Artifacts #
      ###############################################
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: myimage
          path: /tmp

      #########################
      # Load the docker image #
      #########################
      - name: Load image
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a
